#!/bin/bash

if [ "$(uname -r | sed 's/-arch/\.arch/')" != "$(pacman -Q linux | awk '{print $2}')" ]; then
  gum confirm "Linux kernel has been updated. Reboot?" && omanano-state clear re*-required && sudo reboot now

elif [ -f "$HOME/.local/state/omanano/reboot-required" ]; then
  gum confirm "Updates require reboot. Ready?" && omanano-state clear re*-required && sudo reboot now

elif [ -f "$HOME/.local/state/omanano/relaunch-required" ]; then
  gum confirm "Updates require Hyprland relaunch. Ready?" && omanano-state clear re*-required && uwsm stop
fi

for file in "$HOME"/.local/state/omanano/restart-*-required; do
  if [ -f "$file" ]; then
    filename=$(basename "$file")
    service=$(echo "$filename" | sed 's/restart-\(.*\)-required/\1/')
    echo "Restarting $service"
    omanano-state clear "$filename"
    omanano-restart-"$service"
  fi
done
