#!/usr/bin/env bash
# bootstrap.sh — Fix directory-level symlinks for ~/.config and ~/.local
#
# Problem: ~/.config and ~/.local were linked as whole directories to the
# dotfiles repo. This script corrects that by:
#   1. Unlinking the directory-level symlinks
#   2. Recreating them as real directories
#   3. Symlinking managed items individually from the repo into the real dirs
#   4. Moving unmanaged content back out of the repo directory
#
# Run with DRY_RUN=1 to preview without making changes.
# Run from anywhere; DOTFILES defaults to ~/.dotfiles.

set -euo pipefail

DOTFILES="${DOTFILES:-$HOME/.dotfiles}"
DOT_CONFIG="$DOTFILES/dot-config"
DOT_LOCAL="$DOTFILES/dot-local"
DRY_RUN="${DRY_RUN:-0}"

# ── Colours ────────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
    RED=$'\e[31m' GREEN=$'\e[32m' YELLOW=$'\e[33m' BLUE=$'\e[34m' RESET=$'\e[0m'
else
    RED='' GREEN='' YELLOW='' BLUE='' RESET=''
fi
info()  { echo "${BLUE}→${RESET} $*"; }
ok()    { echo "${GREEN}✓${RESET} $*"; }
warn()  { echo "${YELLOW}!${RESET} $*"; }
die()   { echo "${RED}✗${RESET} $*" >&2; exit 1; }

run() {
    if [[ "$DRY_RUN" == "1" ]]; then
        echo "  [dry] $*"
    else
        "$@"
    fi
}

# ── Helpers ────────────────────────────────────────────────────────────────────

# Unlink $1 if it is a directory-level symlink (the mistake we're fixing).
unlink_dir_symlink() {
    local path="$1"
    if [[ -L "$path" && -d "$path" ]]; then
        warn "Unlinking directory symlink: $path → $(readlink "$path")"
        run unlink "$path"
    elif [[ -L "$path" ]]; then
        warn "Dangling symlink at $path, removing"
        run unlink "$path"
    fi
}

# Symlink $1 (source in repo) to $2 (dest in real home dir).
link_item() {
    local src="$1"
    local dest="$2"

    if [[ -L "$dest" ]]; then
        local target
        target="$(readlink "$dest")"
        if [[ "$target" == "$src" ]]; then
            ok "already linked: $(basename "$dest")"
            return 0
        fi
        warn "Stale link $dest → $target  (relinking → $src)"
        run unlink "$dest"
        run ln -s "$src" "$dest"
        ok "relinked: $(basename "$dest")"
    elif [[ -e "$dest" ]]; then
        warn "Real path already exists, skipping: $dest"
    else
        run ln -s "$src" "$dest"
        ok "linked: $(basename "$dest")"
    fi
}

# Move $1 out of the repo directory to $2 in the real home tree.
# Skips if source doesn't exist or destination is already present.
move_out() {
    local src="$1"
    local dest="$2"

    [[ -e "$src" || -L "$src" ]] || return 0   # nothing to move

    if [[ -e "$dest" || -L "$dest" ]]; then
        warn "Destination exists, skipping move: $dest"
        return 0
    fi

    run mkdir -p "$(dirname "$dest")"
    run mv "$src" "$dest"
    ok "moved to real dir: $dest"
}

# ══════════════════════════════════════════════════════════════════════════════
# Sanity checks
# ══════════════════════════════════════════════════════════════════════════════
[[ -d "$DOTFILES" ]] || die "Dotfiles directory not found: $DOTFILES"
[[ -d "$DOT_CONFIG" ]] || die "dot-config not found: $DOT_CONFIG"
[[ -d "$DOT_LOCAL" ]] || die "dot-local not found: $DOT_LOCAL"

[[ "$DRY_RUN" == "1" ]] && info "DRY RUN — no changes will be made"

# ══════════════════════════════════════════════════════════════════════════════
# 1. ~/.config
# ══════════════════════════════════════════════════════════════════════════════
info "=== ~/.config ==="

unlink_dir_symlink "$HOME/.config"
run mkdir -p "$HOME/.config"

# Directories managed in the dotfiles repo — symlink each into ~/.config/
MANAGED_CONFIG=(
    ArchiveNvim
    alacritty
    atuin
    colorschemes
    fish
    gh
    git
    ghostty
    helix
    kitty
    lazynvim
    nvim
    scripts
    shell
    starship
    zed
    zellij
    zsh-abbr
)

for dir in "${MANAGED_CONFIG[@]}"; do
    src="$DOT_CONFIG/$dir"
    if [[ ! -d "$src" ]]; then
        warn "Not found in dotfiles, skipping: $dir"
        continue
    fi
    link_item "$src" "$HOME/.config/$dir"
done

# Directories NOT managed by the repo — move them out of the repo directory
# so they live natively in ~/.config and are never accidentally committed.
MOVE_OUT_CONFIG=(
    AWSVPNClient      # work-specific logs and VPN configs
    cagent            # first-run state
    configstore       # auto-generated by node tools
    containers        # podman connection state
    github-copilot    # auth tokens — never commit!
    pip               # pip.conf has embedded AWS CodeArtifact token — regenerate with codeartifact-login
    uv                # auto-generated receipt from uv installer
)

for dir in "${MOVE_OUT_CONFIG[@]}"; do
    move_out "$DOT_CONFIG/$dir" "$HOME/.config/$dir"
done

# ══════════════════════════════════════════════════════════════════════════════
# 2. ~/.local
# ══════════════════════════════════════════════════════════════════════════════
info "=== ~/.local ==="

unlink_dir_symlink "$HOME/.local"
run mkdir -p "$HOME/.local/bin" "$HOME/.local/share" "$HOME/.local/pipx" "$HOME/.local/state"

# ── ~/.local/bin ───────────────────────────────────────────────────────────────
# Symlink individual tracked scripts; move out machine-specific binaries.

MANAGED_BIN=(
    codeartifact-login
    pip
    pip3
    pip3.12
    sp
)

for f in "${MANAGED_BIN[@]}"; do
    src="$DOT_LOCAL/bin/$f"
    [[ -e "$src" ]] || { warn "Not in dotfiles/bin, skipping: $f"; continue; }
    link_item "$src" "$HOME/.local/bin/$f"
done

# Machine-specific entries: move them back to ~/.local/bin as real files.
# Note: symlinks that pointed into dot-local/pipx/ will break once pipx is
# moved below — run `pipx reinstall-all` afterwards to regenerate them.
MOVE_OUT_BIN=(
    aws-secrets
    aws-secrets_beta
    claude
    terraform
    uv
    uvx
)

for f in "${MOVE_OUT_BIN[@]}"; do
    move_out "$DOT_LOCAL/bin/$f" "$HOME/.local/bin/$f"
done

# ── ~/.local/share/fonts ───────────────────────────────────────────────────────
# Fonts are tracked in the repo; symlink the whole fonts dir.
if [[ -d "$DOT_LOCAL/share/fonts" ]]; then
    link_item "$DOT_LOCAL/share/fonts" "$HOME/.local/share/fonts"
fi

# Runtime share dirs — move out of the repo.
MOVE_OUT_SHARE=(
    atuin       # shell history database
    claude      # Claude app data
    containers  # container runtime data
    fish        # fisher plugin data
    man         # generated man pages
    nvim        # nvim plugin installs (lazy.nvim etc.)
    uv          # uv app data
    zinit       # zinit plugin data
)

for dir in "${MOVE_OUT_SHARE[@]}"; do
    move_out "$DOT_LOCAL/share/$dir" "$HOME/.local/share/$dir"
done

# ── ~/.local/pipx ──────────────────────────────────────────────────────────────
# pipx stores venvs here. Move the whole thing out of the repo.
# After this, the aws-secrets/aws-secrets_beta symlinks in bin will be broken;
# run `pipx reinstall-all` (with PIPX_HOME=~/.local/pipx) to fix them.
move_out "$DOT_LOCAL/pipx" "$HOME/.local/pipx-from-dotfiles"
if [[ -d "$HOME/.local/pipx-from-dotfiles" && ! -d "$HOME/.local/pipx" ]]; then
    run mv "$HOME/.local/pipx-from-dotfiles" "$HOME/.local/pipx"
    ok "pipx data restored to ~/.local/pipx"
elif [[ -d "$HOME/.local/pipx-from-dotfiles" ]]; then
    warn "~/.local/pipx already exists — merge manually with ~/.local/pipx-from-dotfiles"
fi

# ── ~/.local/state ─────────────────────────────────────────────────────────────
# Move each state subdir out individually to avoid clobbering an existing dir.
if [[ -d "$DOT_LOCAL/state" ]]; then
    for item in "$DOT_LOCAL/state"/*/; do
        [[ -d "$item" ]] || continue
        name="$(basename "$item")"
        move_out "$item" "$HOME/.local/state/$name"
    done
fi

# ══════════════════════════════════════════════════════════════════════════════
# 3. Dot-files that live directly in ~/
# ══════════════════════════════════════════════════════════════════════════════
info "=== ~/dot-files ==="

for f in dot-zshrc dot-zprofile; do
    [[ -f "$DOTFILES/$f" ]] || continue
    dest="$HOME/.${f#dot-}"
    link_item "$DOTFILES/$f" "$dest"
done

# dot-zsh plugins dir
if [[ -d "$DOTFILES/dot-zsh" ]]; then
    link_item "$DOTFILES/dot-zsh" "$HOME/.zsh"
fi

# ══════════════════════════════════════════════════════════════════════════════
# Done
# ══════════════════════════════════════════════════════════════════════════════
echo ""
info "=== Done ==="
echo ""
echo "Post-migration checklist:"
echo "  1. Verify ~/.config/github-copilot/ is NOT inside the dotfiles repo"
echo "     (it should now be at ~/.config/github-copilot/ in the real dir)"
echo "  2. If pipx venv symlinks in ~/.local/bin/ are broken, run:"
echo "       PIPX_HOME=~/.local/pipx pipx reinstall-all"
echo "  3. Run \`git status\` in $DOTFILES to confirm no sensitive files are staged"
echo "  4. Check that ~/.config/gh/hosts.yml is NOT committed (it has auth tokens)"
