sidebar_bg = "#1c1b1a"
active_row_bg = "#282726"
selection_bg = "#343331"
panel_bg = "#100f0f"
accent = "#4385be"
red = "#d14d41"
green = "#879a39"
yellow = "#ad8301"
blue = "#4385be"
mauve = "#ce5d97"
teal = "#3aa99f"
peach = "#da702c"
