# Inserts a blank line between shell prompts
add_newline = false

# Change the default prompt format
#format = """$directory $git_branch $character"""
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$character"""

# Set theme
command_timeout = 1000

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](red)'
vimcmd_symbol = "[❮](green)"

# Modules
[directory]
truncation_length = 0
truncate_to_repo = true

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style) '
