/* Generated by theme-switcher-apply from the active theme's SWATCH.
   Edit this template (not the copy in the Firefox profile) and re-apply a
   theme to regenerate. Requires toolkit.legacyUserProfileCustomizations.stylesheets
   in about:config. No live reload - reload the window manually. */

:root {
  --toolbar-bgcolor: #__BG__ !important;
  --toolbar-color: #__FG__ !important;
  --lwt-accent-color: #__BG__ !important;
  --lwt-text-color: #__FG__ !important;
  --tab-selected-bgcolor: #__BG__ !important;
  --tab-selected-textcolor: #__FG__ !important;
  --urlbar-box-bgcolor: #__BG__ !important;
  --urlbar-box-focus-bgcolor: #__BG__ !important;
  --urlbar-box-text-color: #__FG__ !important;
}

#navigator-toolbox,
#TabsToolbar,
#nav-bar,
#titlebar,
#PersonalToolbar {
  background-color: #__BG__ !important;
  color: #__FG__ !important;
}

.tabbrowser-tab[selected="true"] .tab-background {
  background-color: #__BLUE__ !important;
}

#urlbar-background {
  background-color: #__BG__ !important;
  border-color: #__PURPLE__ !important;
}
