#!/bin/bash

sudo cp ~/.local/share/omanano/default/plymouth/* /usr/share/plymouth/themes/omanano/
sudo plymouth-set-default-theme omanano

if command -v limine-mkinitcpio &>/dev/null; then
  sudo limine-mkinitcpio
else
  sudo mkinitcpio -P
fi
