background = rgb(11111b)
base = rgb(1e1e2e)
text = rgb(cdd6f4)
alternate_base = rgb(181825)
bright_text = rgb(bac2de)
accent = rgb(89b4fa)
accent_secondary = rgb(74c7ec)
h1_size = 25
h2_size = 23
h3_size = 20
font_size = 12
small_font_size = 8
#icon_theme = 
