decoration {
    blur {
        enabled = yes
        size = 3
        passes = 1
        new_optimizations = on
    }
    rounding = 5

    # multisample_edges = true

  shadow {
    enabled = yes
    range = 5
    render_power = 1
    color = rgba(16161eee)
  }
}
