#!/usr/bin/sh

status=$(/bin/cat /proc/acpi/button/lid/LID0/state | awk {'print $2'})
monitor=$(xrandr --query | grep 'HDMI1' | awk {'print $2'})

#Workspaces
if [[ $status == "closed" && $monitor == "connected" ]]; then
		bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 10
elif [[ $status == "open" && $monitor == "connected" ]]; then
		bspc monitor eDP1 -d 1 2 3 4 5
		bspc monitor HDMI1 -d 1 2 3 4 5
elif [[ $monitor != "connected" ]]; then
		bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
fi

#Borders
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          20
bspc config normal_border_color "#161616"
bspc config focused_border_color "#acb0b0"

#Configs
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

#Rules
bspc rule -a *:*:'Picture-in-Picture' state=floating sticky=on follow=off focus=on
bspc rule -a *:*:'Picture-in-picture' state=floating sticky=on follow=off focus=on
bspc rule -a firefox:Toolkit state=floating rectangle=widthxheight+x+y
#bspc rule -a Bitwarden desktop=^9 follow=off focus=off

#Autostart
killall sxhkd &
sxhkd &
~/.config/autostart/autostart.sh &
~/.config/polybar/launch.sh &
