# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
#format = """$directory $git_branch $character"""
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$line_break\
$character"""

# Set theme
palette = "flexoki_dark"
command_timeout = 1000

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](red)'
vimcmd_symbol = "[❮](green)"

# Modules
[directory]
truncation_length = 0
truncate_to_repo = true

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style) '

# Paleta de Cores
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.flexoki_dark]
black = "#100f0f"
red = "#d14d41"
green = "#879a39"
yellow = "#d0a215"
blue = "#4385be"
purple = "#ce5d97"
cyan = "#3aa99f"
white = "#878580"
bright_black = "#575653"
bright_red = "#af3029"
bright_green = "#66800b"
bright_yellow = "#ad8301"
bright_blue = "#205ea6"
bright_purple = "#a02f6f"
bright_cyan = "#24837b"
bright_white = "#cecdc3"

[palettes.gruvbox_dark]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
purple = "#b16286"
cyan = "#689d6a"
white = "#a89984"
bright_black = "#928374"
bright_red = "#fb4934"
bright_green = "#b8bb26"
bright_yellow = "#fabd2f"
bright_blue = "#83a598"
bright_purple = "#d3869b"
bright_cyan = "#8ec07c"
bright_white = "#ebdbb2"

[palettes.tokyonight_storm]
black = "#1d202f"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
purple = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"
bright_black = "#4e5575"
bright_red = "#f7768e"
bright_green = "#9ece6a"
bright_yellow = "#e0af68"
bright_blue = "#7aa2f7"
bright_purple = "#bb9af7"
bright_cyan = "#7dcfff"
bright_white = "#c0caf5"

[palettes.kanagawa_wave]
black = "#090618"
red = "#c34043"
green = "#76946a"
yellow = "#c0a36e"
blue = "#7e9cd8"
purple = "#957fb8"
cyan = "#6a9589"
white = "#c8c093"
bright_black = "#727169"
bright_red = "#e82424"
bright_green = "#98bb6c"
bright_yellow = "#e6c384"
bright_blue = "#7fb4ca"
bright_purple = "#938aa9"
bright_cyan = "#7aa89f"
bright_white = "#dcd7ba"

[package]
disabled = true

[python]
format = ' [${pyenv_prefix}(\($virtualenv\) )]($style)'

[gcloud]
disabled = true
