$activeBorderColor = rgb(c6d0f5)
$inactiveBorderColor = rgba(595959aa)
$lockedActiveBorderColor = rgba(f38ba8FF)
$lockedInactiveBorderColor = rgba(f38ba8D0)

general {
    col.active_border = $activeBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
    col.border_locked_active = $lockedActiveBorderColor
    col.border_locked_inactive = $lockedInactiveBorderColor

    groupbar {
        text_color = rgb(cdd6f4)
        text_color_inactive = rgba(cdd6f4D0)
        col.active = rgba(11111BAF)
        col.inactive = rgba(45475aA0)
        col.locked_active = rgba(6c7086dd)
        col.locked_inactive = rgba(45475a70)
    }
}

