[global/wm]

#margin-bottom = 20
#margin-top = 20

include-file = ~/.config/polybar/colors.ini
#include-file = ~/.config/leftwm/themes/current/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini
#include-file = ~/.config/leftwm/themes/current/polybar/modules.ini
include-file = ~/.config/polybar/user_modules.ini
#include-file = ~/.config/leftwm/themes/current/polybar/user_modules.ini

[color]
; general
background 		    = ${colors.bg}
foreground 		    = ${colors.fg}

; workspaces
focused		        = ${colors.focused}
occupied		    = ${colors.occupied}
empty   		    = ${colors.empty}
urgent				= ${colors.red}

; colors
red = ${colors.red}
blue= ${colors.blue}
yellow = ${colors.yellow}
orange = ${colors.orange}
purple = ${colors.purple}
magenta = ${colors.magenta}
black = ${colors.black}
green = ${colors.green}
cyan = ${colors.cyan}
white = ${colors.white}

[bar/main]
monitor = HDMI-0

width = 100%
height = 20
padding-left = 0
padding-right = 0

background = ${color.background}
foreground = ${color.foreground}

tray-position = right
tray-padding = 1

bottom = false

line-size = 1
override-redirect = false
#wm-restack = generic
locale = pt_BR.UTF-8

modules-left   = ewmh spotify
modules-center = time
modules-right  = redshift mic pulseaudio

font-0 = "JetBrainsMono NerdFont:style=Regular:size=10;2"
font-1 = "JetBrainsMono NerdFont:style=Regular:size=10;2"
font-2 = "JetBrainsMono NerdFont:size=19;5"
#font-3 = "Material Icons Outlined:9;4"
#font-4 = "Material Icons Round:9;4"

[settings]
throttle-output = 5
throttle-output-for = 10
screenchange-reload = false
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
pseudo-transparency = false
format-padding = 1
