[module/brightness]
type = custom/script
label = " %output%"
label-padding = 1
label-font = 2
format = <label>
exec = printf $(brillo | cut -d'.' -f1)%%
click-left = redshift -P -O 4800
click-right = redshift -x
scroll-up = brightness up
scroll-down = brightness down
interval = 0.5

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/redshift]
type = custom/text
content= 󰌵
click-left = redshift -P -O 4200
click-right = redshift -x

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/spotify]
type = custom/script
tail = true
interval = 1

format = "%{T2} %{T-}<label>"
exec = ~/.config/scripts/scroll_spotify_status.sh

click-left   = playerctl --player=spotify play-pause &
click-right  = playerctl --player=spotify next &
click-middle = playerctl --player=spotify previous &
scroll-up    = playerctl --player=spotify volume 0.05+ &
scroll-down    = playerctl --player=spotify volume 0.05- &

label-font = 2

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/vpn-status]
type = custom/script
exec = ~/.config/polybar/scripts/vpn_status
interval = 5
format-foreground = ${color.foreground}
format-font = 2

#click-left = sudo openvpn --bind --cd "/home/adriano/Documentos/plusdelivery" --config "plusdelivery.ovpn"
#click-middle = sudo openvpn --bind --cd "/home/adriano/Documentos/plusdelivery" --config "plusdelivery-dev.ovpn"
click-right = sudo killall openvpn

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/mic]
type = custom/script
exec = ~/.config/scripts/micstatus
tail = true
interval = 0.5
format = <label>
label = %output%
label-padding = 1
label-font = 2
click-left = ~/.local/bin/micvolume mute
click-right = pavucontrol
scroll-up = ~/.local/bin/micvolume up
scroll-down = ~/.local/bin/micvolume down

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sound]
type = custom/script
exec = ~/.config/polybar/scripts/soundstatus
tail = true
interval = 0.5
format = <label>
label = %output%
click-left = ~/.local/bin/changevolume mute
click-right = pavucontrol
scroll-up = ~/.local/bin/changevolume up
scroll-down = ~/.local/bin/changevolume down
